title: hyprZona Official Website
description: This is the official site to visit & view original hyprZona products.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hyprZona.github.io" # the base hostname & protocol for your site

# Enable clean URLs
permalink: /:basename/
